// src/components/OutputBar.tsx
import { useEffect, useState } from "preact/hooks";
import { Color, colorFormats } from "../lib/color";
import { setClipboard } from "../lib/util";

/** Props for the OutputBar component */
interface OutputBarProps {
    /** The color to display */
    color: Color;
}

export function OutputBar({ color }: OutputBarProps) {
    const [outputFormat, setOutputFormat] =
        useState<keyof typeof colorFormats>("Hex");
    const [autoCopy, setAutoCopy] = useState(false);

    // Automatically copy the color when the format or color changes
    useEffect(() => {
        if (autoCopy) {
            setClipboard(colorFormats[outputFormat](color));
        }
    }, [outputFormat, color.r, color.g, color.b]);

    return (
        <div class="input-group input-group-lg mb-3">
            <span
                class="input-group-text"
                style={{
                    backgroundColor: `rgb(${color.r}, ${color.g}, ${color.b})`,
                }}
            >
                &nbsp;
            </span>
            <input
                type="text"
                class="form-control"
                value={colorFormats[outputFormat](color)}
                readonly
            />
            <button
                class="btn btn-outline-secondary dropdown-toggle"
                type="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
            >
                {outputFormat}
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
                {Object.keys(colorFormats).map((format) => (
                    <li>
                        <a
                            class="dropdown-item"
                            href="#"
                            onClick={(ev) => {
                                ev.preventDefault();
                                setOutputFormat(
                                    format as keyof typeof colorFormats
                                );
                            }}
                        >
                            {format}
                        </a>
                    </li>
                ))}
            </ul>
            <button
                class="btn btn-success"
                type="button"
                onClick={() => {
                    setClipboard(colorFormats[outputFormat](color));
                }}
            >
                Copy
            </button>
            <button
                class="btn btn-success dropdown-toggle dropdown-toggle-split"
                type="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
            />
            <ul class="dropdown-menu">
                <li>
                    <a
                        class="dropdown-item"
                        href="#"
                        onClick={(ev) => {
                            ev.preventDefault();
                            setAutoCopy(!autoCopy);
                        }}
                    >
                        {autoCopy && <i class="bi bi-check me-2" />}
                        Automatically copy
                    </a>
                </li>
            </ul>
        </div>
    );
}

// src/components/OutputBar.vue
<template lang="pug">
    .input-group.input-group-lg.w-100.mb-3
        input.form-control(
            type="text"
            :value="output"
            ref="inputRef"
            readonly
        )
        .input-group-append
            button.btn.btn-outline-secondary.dropdown-toggle(
                type="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
            ) {{format}}
            .dropdown-menu
                a.dropdown-item(
                    href="#"
                    v-for="(_, k) in outputFormats"
                    :key="k"
                    v-on:click.prevent="format = k"
                ) {{k}}
        .input-group-append
            button.btn.btn-success(
                type="button"
                v-on:click.passive="setClipboard"
            ) Copy
</template>

<script lang="ts">
import { defineComponent, ref, computed, toRefs } from "@vue/composition-api";

const outputFormats = {
    Hex(input: string): string {
        return "#" + input;
    },
    RGB(input: string): string {
        return (
            "rgb(" +
            parseInt(input.substring(0, 2), 16) +
            ", " +
            parseInt(input.substring(2, 4), 16) +
            ", " +
            parseInt(input.substring(4, 6), 16) +
            ")"
        );
    }
};

export default defineComponent({
    props: {
        selectedColor: {
            type: String,
            required: true
        }
    },
    setup(props) {
        const { selectedColor } = toRefs(props);
        const inputRef = ref<HTMLInputElement>();
        const format = ref<keyof typeof outputFormats>("Hex");

        const output = computed(() =>
            outputFormats[format.value](selectedColor.value)
        );

        function setClipboard() {
            const element = inputRef.value;
            if (!element) {
                return;
            }
            element.focus();
            element.select();
            document.execCommand("copy");
        }

        return {
            inputRef,
            format,
            output,
            outputFormats,
            setClipboard
        };
    }
});
</script>
