// src/App.tsx
import React, { useMemo, useRef, useState } from "react";
import data from "./colorpalettes.json";
import { format } from "./typescript-modules/build/StringUtilities";

interface IColorPickerAppProps {
    onChange?: (output: string) => void;
}

const formats = {
    /* eslint-disable no-template-curly-in-string */
    Hex: "#${r:x2}${g:x2}${b:x2}",
    RGB: "rgb(${r:d0}, ${g:d0}, ${b:d0})",
    RGBA: "rgba(${r:d0}, ${g:d0}, ${b:d0}, 1)"
    /* eslint-enable no-template-curly-in-string */
};

const ColorPickerApp: React.FC = () => {
    const outputEl: React.MutableRefObject<HTMLInputElement | null> = useRef(null);
    const [selectedPalette, setSelectedPalette] = useState(Object.keys(data)[0]);
    const [selectedColor, setSelectedColor] = useState("");
    const [selectedFormat, setSelectedFormat] = useState("Hex");
    const [customFormat, setCustomFormat] = useState("");

    const output = useMemo(() => {
        if (!selectedColor) {
            return "";
        }
        const color = {
            r: parseInt(selectedColor.substring(0, 2), 16),
            g: parseInt(selectedColor.substring(2, 4), 16),
            b: parseInt(selectedColor.substring(4, 6), 16)
        };
        return format(
            selectedFormat === "Custom" ? customFormat : formats[selectedFormat as keyof typeof formats],
            color
        );
    }, [selectedColor, selectedFormat, customFormat]);

    function setOutputToClipboard() {
        const el = outputEl.current;
        if (!el) {
            return;
        }
        el.focus();
        el.select();
        document.execCommand("copy");
    }

    return (
        <>
            <h1>
                Color Picker
                <a href="https://lixquid.com" className="btn btn-outline-primary float-right">
                    lixquid.com
                </a>
            </h1>

            <div className="input-group input-group-lg mt-5">
                <input
                    type="text"
                    name="output"
                    id="output"
                    className="form-control"
                    value={output}
                    ref={outputEl}
                    readOnly
                />
                <div className="input-group-append">
                    <button
                        className="btn btn-outline-secondary dropdown-toggle"
                        type="button"
                        data-toggle="dropdown"
                        aria-haspopup="true"
                        aria-expanded="false"
                    >
                        {selectedFormat}
                    </button>
                    <div className="dropdown-menu">
                        {Object.keys(formats).map(format => (
                            <a
                                className="dropdown-item"
                                href="#"
                                onClick={e => {
                                    e.preventDefault();
                                    setSelectedFormat(format);
                                }}
                            >
                                {format}
                            </a>
                        ))}
                        <input
                            type="text"
                            className="dropdown-item form-control"
                            placeholder="Custom"
                            value={customFormat}
                            onChange={e => setCustomFormat(e.target.value)}
                            onFocus={() => setSelectedFormat("Custom")}
                        />
                    </div>
                </div>
                <div className="input-group-append">
                    <button className="btn btn-success" onClick={() => outputEl.current && setOutputToClipboard()}>
                        Copy
                    </button>
                </div>
            </div>

            <div className="card mt-3">
                <div className="card-body">
                    <select className="custom-select">
                        {Object.keys(data).map(name => (
                            <option
                                selected={selectedPalette === name}
                                onClick={e => {
                                    e.preventDefault();
                                    setSelectedPalette(name);
                                }}
                            >
                                {name}
                            </option>
                        ))}
                    </select>
                    {Object.keys(data)
                        .filter(name => name === selectedPalette)
                        .map(name => (
                            <div className="px-4 pt-2">
                                {data[name as keyof typeof data].map(cells => (
                                    <div className="row">
                                        {cells.map(color => (
                                            <button
                                                className="btn btn-secondary col m-1"
                                                style={{ backgroundColor: `#${color}`, height: "2rem" }}
                                                onClick={() => setSelectedColor(color)}
                                            />
                                        ))}
                                    </div>
                                ))}
                            </div>
                        ))}
                </div>
            </div>
        </>
    );
};

export default ColorPickerApp;

// src/App.vue
<template lang="pug">
    .container.my-5.mx-auto
        h1.mb-5
            | Color Picker
            |
            a.btn.btn-outline-primary.float-right(href="https://lixquid.com").
                lixquid.com

        .input-group.input-group-lg.w-100.mb-3
            input.form-control(
                type="text"
                :value="output"
                ref="outputElementRef"
                readonly
            )
            .input-group-append
                button.btn.btn-success(
                    type="button"
                    v-on:click.passive="outputToClipboard"
                ) Copy

        .mb-3
            button.btn.btn-link.dropdown-toggle(
                type="button"
                v-on:click.passive="previewVisible = !previewVisible"
            ) Preview

        .card.mb-5(v-if="previewVisible")
            .card-header Preview
            .card-body.text-center.px-5
                .row
                    .col.text-dark(:style="{background: '#' + selectedColor}")
                        .h1 Example
                    .col.text-light(:style="{background: '#' + selectedColor}")
                        .h1 Example
                .row
                    .col.bg-dark(:style="{color: '#' + selectedColor}")
                        .h1 Example
                    .col.bg-light(:style="{color: '#' + selectedColor}")
                        .h1 Example

        .card.mt-5
            .card-header
                ul.nav.nav-tabs.card-header-tabs
                    li.nav-item
                        a.nav-link.active(
                            href="#"
                            v-on:click.prevent=""
                        ) Palette
            .card-body
                select.custom-select.mb-3(v-model="selectedPalette")
                    option(v-for="(_, palette) in palettes") {{palette}}
                .d-flex(v-for="row in palettes[selectedPalette]")
                    button.palette--box(
                        v-for="c in row"
                        :title="c"
                        :style="{background: '#' + c}"
                        v-on:click.passive="selectedColor = c"
                    )

</template>

<script lang="ts">
import { defineComponent, ref, computed } from "@vue/composition-api";
import palettes from "./colorpalettes.json";

export default defineComponent({
    setup() {
        const outputElementRef = ref<HTMLInputElement>();
        const selectedColor = ref("ffffff");
        const selectedPalette = ref<keyof typeof palettes>(
            Object.keys(palettes)[0]
        );
        const previewVisible = ref(false);

        const output = computed(() => "#" + selectedColor.value);

        function outputToClipboard() {
            const element = outputElementRef.value;
            if (!element) {
                console.log(5);
                return;
            }
            element.focus();
            element.select();
            document.execCommand("copy");
        }

        return {
            selectedColor,
            palettes,
            selectedPalette,
            outputElementRef,
            output,
            outputToClipboard,
            previewVisible
        };
    }
});
</script>

<style lang="stylus" scoped>
.palette--box {
  flex-grow: 1;
  height: 3em;
  border: none;
}
</style>
